apiVersion: v1
kind: Service
metadata:
  name: isens-m3-iqualimeter-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: isens-m3-iqualimeter
  ports:
    - port: 5000
      targetPort: 5000
