apiVersion: apps/v1
kind: Deployment
metadata:
  name: isens-m3-iqualimeter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: isens-m3-iqualimeter
  template:
    metadata:
      labels:
        app: isens-m3-iqualimeter
    spec:
      containers:
        - name: isens-m3-iqualimeter-container
          image: isensacr.azurecr.io/isens-m3-py
          ports:
            - containerPort: 5000
